export enum AssetBookItemStatus {
    IN_USE = "IN_USE",
    TRANSFERRED = "TRANSFERRED",
    LIQUIDATED = "LIQUIDATED",
    MISSING = "MISSING",
    DAMAGED = "DAMAGED",
    LOST = "LOST",
    PROPOSED_LIQUIDATION = "PROPOSED_LIQUIDATION",
    MOVED = "MOVED",
}