export const PermissionConstants = {
    PERM_REMOVE_USER: 'PERM_REMOVE_USER',
    PERM_CREATE_USER: 'PERM_CREATE_USER',
    PERM_UPDATE_USER: 'PERM_UPDATE_USER',
    PERM_VIEW_USER: 'PERM_VIEW_USER',

    PERM_CREATE_ROLE: 'PERM_CREATE_ROLE',
    PERM_UPDATE_ROLE: 'PERM_UPDATE_ROLE',
    PERM_VIEW_ROLE: 'PERM_VIEW_ROLE',
    PERM_REMOVE_ROLE: 'PERM_REMOVE_ROLE',

    PERM_CREATE_PERMISSION: 'PERM_CREATE_PERMISSION',
    PERM_UPDATE_PERMISSION: 'PERM_UPDATE_PERMISSION',
    PERM_VIEW_PERMISSION: 'PERM_VIEW_PERMISSION',
    PERM_REMOVE_PERMISSION: 'PERM_REMOVE_PERMISSION',
}