export const PermissionConstants = {
    PERM_REMOVE_USER: 'PERM_REMOVE_USER',
    PERM_CREATE_USER: 'PERM_CREATE_USER',
    PERM_UPDATE_USER: 'PERM_UPDATE_USER',
    PERM_VIEW_USER: 'PERM_VIEW_USER',

    PERM_CREATE_ROLE: 'PERM_CREATE_ROLE',
    PERM_UPDATE_ROLE: 'PERM_UPDATE_ROLE',
    PERM_VIEW_ROLE: 'PERM_VIEW_ROLE',
    PERM_REMOVE_ROLE: 'PERM_REMOVE_ROLE',

    PERM_CREATE_PERMISSION: 'PERM_CREATE_PERMISSION',
    PERM_UPDATE_PERMISSION: 'PERM_UPDATE_PERMISSION',
    PERM_VIEW_PERMISSION: 'PERM_VIEW_PERMISSION',
    PERM_REMOVE_PERMISSION: 'PERM_REMOVE_PERMISSION',

    PERM_CREATE_CATEGORY: 'PERM_CREATE_CATEGORY',
    PERM_UPDATE_CATEGORY: 'PERM_UPDATE_CATEGORY',
    PERM_VIEW_CATEGORY: 'PERM_VIEW_CATEGORY',
    PERM_REMOVE_CATEGORY: 'PERM_REMOVE_CATEGORY',

    PERM_CREATE_UNIT: 'PERM_CREATE_UNIT',
    PERM_UPDATE_UNIT: 'PERM_UPDATE_UNIT',
    PERM_VIEW_UNIT: 'PERM_VIEW_UNIT',
    PERM_REMOVE_UNIT: 'PERM_REMOVE_UNIT',

    PERM_CREATE_ROOM: 'PERM_CREATE_ROOM',
    PERM_UPDATE_ROOM: 'PERM_UPDATE_ROOM',
    PERM_VIEW_ROOM: 'PERM_VIEW_ROOM',
    PERM_REMOVE_ROOM: 'PERM_REMOVE_ROOM',

    PERM_UPDATE_ASSET: 'PERM_UPDATE_ASSET',
    PERM_VIEW_ASSET: 'PERM_VIEW_ASSET',
    PERM_REMOVE_ASSET: 'PERM_REMOVE_ASSET',
    PERM_IDENTIFY_ASSET: 'PERM_IDENTIFY_ASSET',
    PERM_UPDATE_RFID: 'PERM_UPDATE_RFID',
    PERM_REMOVE_RFID: 'PERM_REMOVE_RFID',
    PERM_IMPORT_ASSET: 'PERM_IMPORT_ASSET',

    PERM_CREATE_INVENTORY: 'PERM_CREATE_INVENTORY',
    PERM_UPDATE_INVENTORY: 'PERM_UPDATE_INVENTORY',
    PERM_VIEW_INVENTORY: 'PERM_VIEW_INVENTORY',
    PERM_REMOVE_INVENTORY: 'PERM_REMOVE_INVENTORY',

    // Inventory Group Permissions
    PERM_CREATE_INVENTORY_GROUP: 'PERM_CREATE_INVENTORY_GROUP',
    PERM_UPDATE_INVENTORY_GROUP: 'PERM_UPDATE_INVENTORY_GROUP',
    PERM_VIEW_INVENTORY_GROUP: 'PERM_VIEW_INVENTORY_GROUP',
    PERM_REMOVE_INVENTORY_GROUP: 'PERM_REMOVE_INVENTORY_GROUP',
    PERM_ASSIGN_INVENTORY_GROUP: 'PERM_ASSIGN_INVENTORY_GROUP',
    PERM_MANAGE_GROUP_MEMBERS: 'PERM_MANAGE_GROUP_MEMBERS',

    // Inventory Sub Permissions
    PERM_CREATE_INVENTORY_SUB: 'PERM_CREATE_INVENTORY_SUB',
    PERM_UPDATE_INVENTORY_SUB: 'PERM_UPDATE_INVENTORY_SUB',
    PERM_VIEW_INVENTORY_SUB: 'PERM_VIEW_INVENTORY_SUB',
    PERM_REMOVE_INVENTORY_SUB: 'PERM_REMOVE_INVENTORY_SUB',
    PERM_MANAGE_SUB_MEMBERS: 'PERM_MANAGE_SUB_MEMBERS',

    // Inventory Committee Permissions
    PERM_APPROVE_INVENTORY_RESULT: 'PERM_APPROVE_INVENTORY_RESULT',
    PERM_REVIEW_INVENTORY_REPORT: 'PERM_REVIEW_INVENTORY_REPORT',
    PERM_FINALIZE_INVENTORY: 'PERM_FINALIZE_INVENTORY',
}